<?php
/**
 * Copyright (c) 2017, Nosto Solutions Ltd
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Nosto Solutions Ltd <contact@nosto.com>
 * @copyright 2017 Nosto Solutions Ltd
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 *
 */

/** @var \Nosto\Tagging\Block\Email $this */
?>
<!-- templateVersion 2.0.8 -->
<style type="text/css">
    /* Header styling */
    .nostoHeader {
        font-family: Arial;
        font-size: 24px;
        font-weight: normal;
        text-align: CENTER;
        color: #000000;
        padding: 20px 0 20px 0 !important;
        margin: 0 !important;
    }
    .nostoTemplateRow {
        display: block !important;
        width: 100% !important;
        table-layout: fixed !important;
    }
    .nostoTemplateColumnContainer,
    .nostoTemplateColumn {
        display: inline-table !important;
    }
    .nostoTemplateColumnContainer {
        text-align: center !important;
    }

    /* Mobile styling */
    @media only screen and (max-width: 480px) {
        .nostoTemplateWrapper {
            width: 100% !important;
        }
        .nostoTemplateColumnContainer {
            max-width: 49.5% !important;
        }
        .nostoImageDescription {
            max-width: 100% !important;
        }

        .nostoImageProductContainer {
            height: 190px !important;
        }
        .nostoImageProduct {
            max-height: 190px !important;
        }
    }

    @media only screen and (max-width: 400px) {
        .nostoImageProductContainer {
            height: 180px !important;
        }
        .nostoImageProduct {
            max-height: 180px !important;
        }
    }
    @media only screen and (max-width: 380px) {
        .nostoImageProductContainer {
            height: 170px !important;
        }
        .nostoImageProduct {
            max-height: 170px !important;
        }
    }
    @media only screen and (max-width: 360px) {
        .nostoImageProductContainer {
            height: 160px !important;
        }
        .nostoImageProduct {
            max-height: 160px !important;
        }
    }
    @media only screen and (max-width: 340px) {
        .nostoImageProductContainer {
            height: 150px !important;
        }
        .nostoImageProduct {
            max-height: 150px !important;
        }
    }
    @media only screen and (max-width: 320px) {
        .nostoImageProductContainer {
            height: 140px !important;
        }
        .nostoImageProduct {
            max-height: 140px !important;
        }
    }
    @media only screen and (max-width: 300px) {
        .nostoImageProductContainer {
            height: 130px !important;
        }
        .nostoImageProduct {
            max-height: 130px !important;
        }
    }

</style>